#!/bin/sh

NONE=$'\033[0m'    # unsets color to term's fg color
# regular colors
K=$'\033[0;30m'    # black
R=$'\033[0;31m'    # red
G=$'\033[0;32m'    # green
Y=$'\033[0;33m'    # yellow
B=$'\033[0;34m'    # blue
M=$'\033[0;35m'    # magenta
C=$'\033[0;36m'    # cyan
W=$'\033[0;37m'    # white

# emphasized (bolded) colors
EMK=$'\033[1;30m'
EMR=$'\033[1;31m'
EMG=$'\033[1;32m'
EMY=$'\033[1;33m'
EMB=$'\033[1;34m'
EMM=$'\033[1;35m'
EMC=$'\033[1;36m'
EMW=$'\033[1;37m'

# background colors
BGK=$'\033[40m'
BGR=$'\033[41m'
BGG=$'\033[42m'
BGY=$'\033[43m'
BGB=$'\033[44m'
BGM=$'\033[45m'
BGC=$'\033[46m'
BGW=$'\033[47m'

#grep  -r -n --color=auto $1 $2
#grep  -r -n --color=auto $1 | sed 's/:/ : /'
#grep  -r -n --color=auto $1 | sed 's/:\(.*\):/ +\1 : /g'
#grep  -r -n --color=auto $1 | awk '{print $1+$2 $3}'
#grep -r -n --color=auto $@ | sed 's/:\([0-9]*\):/ +\1 : /g' | grep --color=auto $1
grep -r -n --color=auto "$@" | sed "s|\([_\/\.a-zA-Z0-9]*\):\([0-9]*\):\(.*\)$1\(.*\)|$M\1$C+$G\2 $C:$NONE \3$EMR$1$NONE\4|"
